# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _lnetconfig
else:
    import _lnetconfig

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def lutf_parse_nidlist(str, len, max_nids):
    return _lnetconfig.lutf_parse_nidlist(str, len, max_nids)

def lutf_nid2str(nid):
    return _lnetconfig.lutf_nid2str(nid)
_LIBC_LIMITS_H_ = _lnetconfig._LIBC_LIMITS_H_
MB_LEN_MAX = _lnetconfig.MB_LEN_MAX
_LIMITS_H = _lnetconfig._LIMITS_H
CHAR_BIT = _lnetconfig.CHAR_BIT
SCHAR_MIN = _lnetconfig.SCHAR_MIN
SCHAR_MAX = _lnetconfig.SCHAR_MAX
UCHAR_MAX = _lnetconfig.UCHAR_MAX
CHAR_MIN = _lnetconfig.CHAR_MIN
CHAR_MAX = _lnetconfig.CHAR_MAX
SHRT_MIN = _lnetconfig.SHRT_MIN
SHRT_MAX = _lnetconfig.SHRT_MAX
USHRT_MAX = _lnetconfig.USHRT_MAX
INT_MAX = _lnetconfig.INT_MAX
UINT_MAX = _lnetconfig.UINT_MAX
LONG_MAX = _lnetconfig.LONG_MAX
LONG_MIN = _lnetconfig.LONG_MIN
ULONG_MAX = _lnetconfig.ULONG_MAX
CYAML_TYPE_FALSE = _lnetconfig.CYAML_TYPE_FALSE
CYAML_TYPE_TRUE = _lnetconfig.CYAML_TYPE_TRUE
CYAML_TYPE_NULL = _lnetconfig.CYAML_TYPE_NULL
CYAML_TYPE_NUMBER = _lnetconfig.CYAML_TYPE_NUMBER
CYAML_TYPE_STRING = _lnetconfig.CYAML_TYPE_STRING
CYAML_TYPE_ARRAY = _lnetconfig.CYAML_TYPE_ARRAY
CYAML_TYPE_OBJECT = _lnetconfig.CYAML_TYPE_OBJECT
class cYAML(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cy_next = property(_lnetconfig.cYAML_cy_next_get, _lnetconfig.cYAML_cy_next_set)
    cy_prev = property(_lnetconfig.cYAML_cy_prev_get, _lnetconfig.cYAML_cy_prev_set)
    cy_child = property(_lnetconfig.cYAML_cy_child_get, _lnetconfig.cYAML_cy_child_set)
    cy_type = property(_lnetconfig.cYAML_cy_type_get, _lnetconfig.cYAML_cy_type_set)
    cy_valuestring = property(_lnetconfig.cYAML_cy_valuestring_get, _lnetconfig.cYAML_cy_valuestring_set)
    cy_valueint = property(_lnetconfig.cYAML_cy_valueint_get, _lnetconfig.cYAML_cy_valueint_set)
    cy_valuedouble = property(_lnetconfig.cYAML_cy_valuedouble_get, _lnetconfig.cYAML_cy_valuedouble_set)
    cy_string = property(_lnetconfig.cYAML_cy_string_get, _lnetconfig.cYAML_cy_string_set)
    cy_user_data = property(_lnetconfig.cYAML_cy_user_data_get, _lnetconfig.cYAML_cy_user_data_set)

    def __init__(self):
        _lnetconfig.cYAML_swiginit(self, _lnetconfig.new_cYAML())
    __swig_destroy__ = _lnetconfig.delete_cYAML

# Register cYAML in _lnetconfig:
_lnetconfig.cYAML_swigregister(cYAML)


def cYAML_load(file, debug):
    return _lnetconfig.cYAML_load(file, debug)

def cYAML_build_tree(path, yaml_blk, yaml_blk_size, debug):
    return _lnetconfig.cYAML_build_tree(path, yaml_blk, yaml_blk_size, debug)

def cYAML_print_tree(node):
    return _lnetconfig.cYAML_print_tree(node)

def cYAML_print_tree2file(f, node):
    return _lnetconfig.cYAML_print_tree2file(f, node)

def cYAML_dump(node):
    return _lnetconfig.cYAML_dump(node)

def cYAML_free_tree(node):
    return _lnetconfig.cYAML_free_tree(node)

def cYAML_get_object_item(parent, name):
    return _lnetconfig.cYAML_get_object_item(parent, name)

def cYAML_get_next_seq_item(seq):
    return _lnetconfig.cYAML_get_next_seq_item(seq)

def cYAML_is_sequence(node):
    return _lnetconfig.cYAML_is_sequence(node)

def cYAML_find_object(root, key):
    return _lnetconfig.cYAML_find_object(root, key)

def cYAML_clean_usr_data(node, free_cb):
    return _lnetconfig.cYAML_clean_usr_data(node, free_cb)

def cYAML_create_object(parent, key):
    return _lnetconfig.cYAML_create_object(parent, key)

def cYAML_create_seq(parent, key):
    return _lnetconfig.cYAML_create_seq(parent, key)

def cYAML_create_seq_item(seq):
    return _lnetconfig.cYAML_create_seq_item(seq)

def cYAML_create_string(parent, key, value):
    return _lnetconfig.cYAML_create_string(parent, key, value)

def cYAML_create_number(parent, key, value):
    return _lnetconfig.cYAML_create_number(parent, key, value)

def cYAML_insert_sibling(root, sibling):
    return _lnetconfig.cYAML_insert_sibling(root, sibling)

def cYAML_insert_child(parent, node):
    return _lnetconfig.cYAML_insert_child(parent, node)

def cYAML_build_error(rc, seq_no, cmd, entity, err_str):
    return _lnetconfig.cYAML_build_error(rc, seq_no, cmd, entity, err_str)
LUSTRE_CFG_RC_NO_ERR = _lnetconfig.LUSTRE_CFG_RC_NO_ERR
LUSTRE_CFG_RC_BAD_PARAM = _lnetconfig.LUSTRE_CFG_RC_BAD_PARAM
LUSTRE_CFG_RC_MISSING_PARAM = _lnetconfig.LUSTRE_CFG_RC_MISSING_PARAM
LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM = _lnetconfig.LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM
LUSTRE_CFG_RC_OUT_OF_MEM = _lnetconfig.LUSTRE_CFG_RC_OUT_OF_MEM
LUSTRE_CFG_RC_GENERIC_ERR = _lnetconfig.LUSTRE_CFG_RC_GENERIC_ERR
LUSTRE_CFG_RC_NO_MATCH = _lnetconfig.LUSTRE_CFG_RC_NO_MATCH
LUSTRE_CFG_RC_MATCH = _lnetconfig.LUSTRE_CFG_RC_MATCH
LUSTRE_CFG_RC_SKIP = _lnetconfig.LUSTRE_CFG_RC_SKIP
LUSTRE_CFG_RC_LAST_ELEM = _lnetconfig.LUSTRE_CFG_RC_LAST_ELEM
LUSTRE_CFG_RC_MARSHAL_FAIL = _lnetconfig.LUSTRE_CFG_RC_MARSHAL_FAIL
CONFIG_CMD = _lnetconfig.CONFIG_CMD
UNCONFIG_CMD = _lnetconfig.UNCONFIG_CMD
ADD_CMD = _lnetconfig.ADD_CMD
DEL_CMD = _lnetconfig.DEL_CMD
SHOW_CMD = _lnetconfig.SHOW_CMD
DBG_CMD = _lnetconfig.DBG_CMD
MANAGE_CMD = _lnetconfig.MANAGE_CMD
MAX_NUM_IPS = _lnetconfig.MAX_NUM_IPS
INT_STRING_LEN = _lnetconfig.INT_STRING_LEN
LNET_DEFAULT_INDENT = _lnetconfig.LNET_DEFAULT_INDENT
modparam_path = _lnetconfig.modparam_path
o2ib_modparam_path = _lnetconfig.o2ib_modparam_path
gni_nid_path = _lnetconfig.gni_nid_path
LNETCTL_CONFIG_CMD = _lnetconfig.LNETCTL_CONFIG_CMD
LNETCTL_UNCONFIG_CMD = _lnetconfig.LNETCTL_UNCONFIG_CMD
LNETCTL_ADD_CMD = _lnetconfig.LNETCTL_ADD_CMD
LNETCTL_DEL_CMD = _lnetconfig.LNETCTL_DEL_CMD
LNETCTL_SHOW_CMD = _lnetconfig.LNETCTL_SHOW_CMD
LNETCTL_DBG_CMD = _lnetconfig.LNETCTL_DBG_CMD
LNETCTL_MANAGE_CMD = _lnetconfig.LNETCTL_MANAGE_CMD
LNETCTL_LAST_CMD = _lnetconfig.LNETCTL_LAST_CMD
LNET_MAX_NIDS_PER_PEER = _lnetconfig.LNET_MAX_NIDS_PER_PEER
class lnet_dlc_network_descr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    network_on_rule = property(_lnetconfig.lnet_dlc_network_descr_network_on_rule_get, _lnetconfig.lnet_dlc_network_descr_network_on_rule_set)
    nw_id = property(_lnetconfig.lnet_dlc_network_descr_nw_id_get, _lnetconfig.lnet_dlc_network_descr_nw_id_set)
    nw_intflist = property(_lnetconfig.lnet_dlc_network_descr_nw_intflist_get, _lnetconfig.lnet_dlc_network_descr_nw_intflist_set)

    def __init__(self):
        _lnetconfig.lnet_dlc_network_descr_swiginit(self, _lnetconfig.new_lnet_dlc_network_descr())
    __swig_destroy__ = _lnetconfig.delete_lnet_dlc_network_descr

# Register lnet_dlc_network_descr in _lnetconfig:
_lnetconfig.lnet_dlc_network_descr_swigregister(lnet_dlc_network_descr)

class lnet_dlc_intf_descr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    intf_on_network = property(_lnetconfig.lnet_dlc_intf_descr_intf_on_network_get, _lnetconfig.lnet_dlc_intf_descr_intf_on_network_set)
    intf_name = property(_lnetconfig.lnet_dlc_intf_descr_intf_name_get, _lnetconfig.lnet_dlc_intf_descr_intf_name_set)
    cpt_expr = property(_lnetconfig.lnet_dlc_intf_descr_cpt_expr_get, _lnetconfig.lnet_dlc_intf_descr_cpt_expr_set)

    def __init__(self):
        _lnetconfig.lnet_dlc_intf_descr_swiginit(self, _lnetconfig.new_lnet_dlc_intf_descr())
    __swig_destroy__ = _lnetconfig.delete_lnet_dlc_intf_descr

# Register lnet_dlc_intf_descr in _lnetconfig:
_lnetconfig.lnet_dlc_intf_descr_swigregister(lnet_dlc_intf_descr)

class lnet_ud_net_descr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    udn_net_type = property(_lnetconfig.lnet_ud_net_descr_udn_net_type_get, _lnetconfig.lnet_ud_net_descr_udn_net_type_set)
    udn_net_num_range = property(_lnetconfig.lnet_ud_net_descr_udn_net_num_range_get, _lnetconfig.lnet_ud_net_descr_udn_net_num_range_set)

    def __init__(self):
        _lnetconfig.lnet_ud_net_descr_swiginit(self, _lnetconfig.new_lnet_ud_net_descr())
    __swig_destroy__ = _lnetconfig.delete_lnet_ud_net_descr

# Register lnet_ud_net_descr in _lnetconfig:
_lnetconfig.lnet_ud_net_descr_swigregister(lnet_ud_net_descr)

class lnet_ud_nid_descr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ud_net_id = property(_lnetconfig.lnet_ud_nid_descr_ud_net_id_get, _lnetconfig.lnet_ud_nid_descr_ud_net_id_set)
    ud_addr_range = property(_lnetconfig.lnet_ud_nid_descr_ud_addr_range_get, _lnetconfig.lnet_ud_nid_descr_ud_addr_range_set)

    def __init__(self):
        _lnetconfig.lnet_ud_nid_descr_swiginit(self, _lnetconfig.new_lnet_ud_nid_descr())
    __swig_destroy__ = _lnetconfig.delete_lnet_ud_nid_descr

# Register lnet_ud_nid_descr in _lnetconfig:
_lnetconfig.lnet_ud_nid_descr_swigregister(lnet_ud_nid_descr)

class lnet_udsp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    udsp_on_list = property(_lnetconfig.lnet_udsp_udsp_on_list_get, _lnetconfig.lnet_udsp_udsp_on_list_set)
    udsp_idx = property(_lnetconfig.lnet_udsp_udsp_idx_get, _lnetconfig.lnet_udsp_udsp_idx_set)
    udsp_src = property(_lnetconfig.lnet_udsp_udsp_src_get, _lnetconfig.lnet_udsp_udsp_src_set)
    udsp_dst = property(_lnetconfig.lnet_udsp_udsp_dst_get, _lnetconfig.lnet_udsp_udsp_dst_set)
    udsp_rte = property(_lnetconfig.lnet_udsp_udsp_rte_get, _lnetconfig.lnet_udsp_udsp_rte_set)
    udsp_action_type = property(_lnetconfig.lnet_udsp_udsp_action_type_get, _lnetconfig.lnet_udsp_udsp_action_type_set)
    udsp_action = property(_lnetconfig.lnet_udsp_udsp_action_get)

    def __init__(self):
        _lnetconfig.lnet_udsp_swiginit(self, _lnetconfig.new_lnet_udsp())
    __swig_destroy__ = _lnetconfig.delete_lnet_udsp

# Register lnet_udsp in _lnetconfig:
_lnetconfig.lnet_udsp_swigregister(lnet_udsp)

class lnet_udsp_udsp_action(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    udsp_priority = property(_lnetconfig.lnet_udsp_udsp_action_udsp_priority_get, _lnetconfig.lnet_udsp_udsp_action_udsp_priority_set)

    def __init__(self):
        _lnetconfig.lnet_udsp_udsp_action_swiginit(self, _lnetconfig.new_lnet_udsp_udsp_action())
    __swig_destroy__ = _lnetconfig.delete_lnet_udsp_udsp_action

# Register lnet_udsp_udsp_action in _lnetconfig:
_lnetconfig.lnet_udsp_udsp_action_swigregister(lnet_udsp_udsp_action)

class lnet_udsp_action(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    udsp_priority = property(_lnetconfig.lnet_udsp_action_udsp_priority_get, _lnetconfig.lnet_udsp_action_udsp_priority_set)

    def __init__(self):
        _lnetconfig.lnet_udsp_action_swiginit(self, _lnetconfig.new_lnet_udsp_action())
    __swig_destroy__ = _lnetconfig.delete_lnet_udsp_action

# Register lnet_udsp_action in _lnetconfig:
_lnetconfig.lnet_udsp_action_swigregister(lnet_udsp_action)


def lustre_lnet_config_lib_init():
    return _lnetconfig.lustre_lnet_config_lib_init()

def lustre_lnet_config_lib_uninit():
    return _lnetconfig.lustre_lnet_config_lib_uninit()

def lustre_lnet_config_ni_system(up, load_ni_from_mod, seq_no):
    return _lnetconfig.lustre_lnet_config_ni_system(up, load_ni_from_mod, seq_no)

def lustre_lnet_config_route(nw, gw, hops, prio, sen, seq_no):
    return _lnetconfig.lustre_lnet_config_route(nw, gw, hops, prio, sen, seq_no)

def lustre_lnet_del_route(nw, gw, seq_no):
    return _lnetconfig.lustre_lnet_del_route(nw, gw, seq_no)

def lustre_lnet_show_route(nw, gw, hops, prio, detail, seq_no, backup):
    return _lnetconfig.lustre_lnet_show_route(nw, gw, hops, prio, detail, seq_no, backup)

def lustre_lnet_config_ni(nw_descr, global_cpts, ip2net, tunables, seq_no):
    return _lnetconfig.lustre_lnet_config_ni(nw_descr, global_cpts, ip2net, tunables, seq_no)

def lustre_lnet_del_ni(nw, seq_no):
    return _lnetconfig.lustre_lnet_del_ni(nw, seq_no)

def lustre_lnet_show_net(nw, detail, seq_no, backup):
    return _lnetconfig.lustre_lnet_show_net(nw, detail, seq_no, backup)

def lustre_lnet_enable_routing(enable, seq_no):
    return _lnetconfig.lustre_lnet_enable_routing(enable, seq_no)

def lustre_lnet_config_numa_range(range, seq_no):
    return _lnetconfig.lustre_lnet_config_numa_range(range, seq_no)

def lustre_lnet_show_numa_range(seq_no):
    return _lnetconfig.lustre_lnet_show_numa_range(seq_no)

def lustre_lnet_config_ni_healthv(value, all, ni_nid, seq_no):
    return _lnetconfig.lustre_lnet_config_ni_healthv(value, all, ni_nid, seq_no)

def lustre_lnet_config_ni_conns_per_peer(value, all, ni_nid, seq_no):
    return _lnetconfig.lustre_lnet_config_ni_conns_per_peer(value, all, ni_nid, seq_no)

def lustre_lnet_config_peer_ni_healthv(value, all, pni_nid, seq_no):
    return _lnetconfig.lustre_lnet_config_peer_ni_healthv(value, all, pni_nid, seq_no)

def lustre_lnet_config_recov_intrv(intrv, seq_no):
    return _lnetconfig.lustre_lnet_config_recov_intrv(intrv, seq_no)

def lustre_lnet_show_recov_intrv(seq_no):
    return _lnetconfig.lustre_lnet_show_recov_intrv(seq_no)

def lustre_lnet_config_rtr_sensitivity(sen, seq_no):
    return _lnetconfig.lustre_lnet_config_rtr_sensitivity(sen, seq_no)

def lustre_lnet_config_hsensitivity(sen, seq_no):
    return _lnetconfig.lustre_lnet_config_hsensitivity(sen, seq_no)

def lustre_lnet_show_hsensitivity(seq_no):
    return _lnetconfig.lustre_lnet_show_hsensitivity(seq_no)

def lustre_lnet_show_rtr_sensitivity(seq_no):
    return _lnetconfig.lustre_lnet_show_rtr_sensitivity(seq_no)

def lustre_lnet_config_transaction_to(timeout, seq_no):
    return _lnetconfig.lustre_lnet_config_transaction_to(timeout, seq_no)

def lustre_lnet_show_transaction_to(seq_no):
    return _lnetconfig.lustre_lnet_show_transaction_to(seq_no)

def lustre_lnet_config_retry_count(count, seq_no):
    return _lnetconfig.lustre_lnet_config_retry_count(count, seq_no)

def lustre_lnet_show_retry_count(seq_no):
    return _lnetconfig.lustre_lnet_show_retry_count(seq_no)

def lustre_lnet_show_lnd_timeout(seq_no):
    return _lnetconfig.lustre_lnet_show_lnd_timeout(seq_no)

def lustre_lnet_show_local_ni_recovq(seq_no):
    return _lnetconfig.lustre_lnet_show_local_ni_recovq(seq_no)

def lustre_lnet_show_peer_ni_recovq(seq_no):
    return _lnetconfig.lustre_lnet_show_peer_ni_recovq(seq_no)

def lustre_lnet_config_response_tracking(count, seq_no):
    return _lnetconfig.lustre_lnet_config_response_tracking(count, seq_no)

def lustre_lnet_show_response_tracking(seq_no):
    return _lnetconfig.lustre_lnet_show_response_tracking(seq_no)

def lustre_lnet_config_recovery_limit(val, seq_no):
    return _lnetconfig.lustre_lnet_config_recovery_limit(val, seq_no)

def lustre_lnet_show_recovery_limit(seq_no):
    return _lnetconfig.lustre_lnet_show_recovery_limit(seq_no)

def lustre_lnet_show_max_recovery_ping_interval(seq_no):
    return _lnetconfig.lustre_lnet_show_max_recovery_ping_interval(seq_no)

def lustre_lnet_config_max_intf(max, seq_no):
    return _lnetconfig.lustre_lnet_config_max_intf(max, seq_no)

def lustre_lnet_show_max_intf(seq_no):
    return _lnetconfig.lustre_lnet_show_max_intf(seq_no)

def lustre_lnet_calc_service_id(service_id):
    return _lnetconfig.lustre_lnet_calc_service_id(service_id)

def lustre_lnet_setup_mrrouting():
    return _lnetconfig.lustre_lnet_setup_mrrouting()

def lustre_lnet_calc_cpt_of_nid(nidc, ncpts):
    return _lnetconfig.lustre_lnet_calc_cpt_of_nid(nidc, ncpts)

def lustre_lnet_config_discovery(enable, seq_no):
    return _lnetconfig.lustre_lnet_config_discovery(enable, seq_no)

def lustre_lnet_show_discovery(seq_no):
    return _lnetconfig.lustre_lnet_show_discovery(seq_no)

def lustre_lnet_config_drop_asym_route(drop, seq_no):
    return _lnetconfig.lustre_lnet_config_drop_asym_route(drop, seq_no)

def lustre_lnet_show_drop_asym_route(seq_no):
    return _lnetconfig.lustre_lnet_show_drop_asym_route(seq_no)

def lustre_lnet_config_buffers(tiny, small, large, seq_no):
    return _lnetconfig.lustre_lnet_config_buffers(tiny, small, large, seq_no)

def lustre_lnet_config_max_recovery_ping_interval(interval, seq_no):
    return _lnetconfig.lustre_lnet_config_max_recovery_ping_interval(interval, seq_no)

def lustre_lnet_show_routing(seq_no, backup):
    return _lnetconfig.lustre_lnet_show_routing(seq_no, backup)

def lustre_lnet_show_stats(seq_no):
    return _lnetconfig.lustre_lnet_show_stats(seq_no)

def lustre_lnet_reset_stats(seq_no):
    return _lnetconfig.lustre_lnet_reset_stats(seq_no)

def lustre_lnet_modify_peer(prim_nid, nids, is_mr, cmd, force, seq_no):
    return _lnetconfig.lustre_lnet_modify_peer(prim_nid, nids, is_mr, cmd, force, seq_no)

def lustre_lnet_show_peer(knid, detail, seq_no, backup):
    return _lnetconfig.lustre_lnet_show_peer(knid, detail, seq_no, backup)

def lustre_lnet_list_peer(seq_no):
    return _lnetconfig.lustre_lnet_list_peer(seq_no)

def lustre_lnet_ping_nid(pnid, src_nidstr, timeout, seq_no):
    return _lnetconfig.lustre_lnet_ping_nid(pnid, src_nidstr, timeout, seq_no)

def lustre_lnet_discover_nid(pnid, force, seq_no):
    return _lnetconfig.lustre_lnet_discover_nid(pnid, force, seq_no)

def lustre_yaml_config(f):
    return _lnetconfig.lustre_yaml_config(f)

def lustre_yaml_del(f):
    return _lnetconfig.lustre_yaml_del(f)

def lustre_yaml_show(f):
    return _lnetconfig.lustre_yaml_show(f)

def lustre_yaml_exec(f):
    return _lnetconfig.lustre_yaml_exec(f)
class nid_node(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nidstr = property(_lnetconfig.nid_node_nidstr_get, _lnetconfig.nid_node_nidstr_set)
    children = property(_lnetconfig.nid_node_children_get, _lnetconfig.nid_node_children_set)
    list = property(_lnetconfig.nid_node_list_get, _lnetconfig.nid_node_list_set)

    def __init__(self):
        _lnetconfig.nid_node_swiginit(self, _lnetconfig.new_nid_node())
    __swig_destroy__ = _lnetconfig.delete_nid_node

# Register nid_node in _lnetconfig:
_lnetconfig.nid_node_swigregister(nid_node)


def lustre_lnet_parse_nid_range(head, nidstr):
    return _lnetconfig.lustre_lnet_parse_nid_range(head, nidstr)

def lustre_lnet_free_list(head):
    return _lnetconfig.lustre_lnet_free_list(head)

def yaml_emitter_set_output_netlink(emitter, nl, family, version, cmd, flags):
    return _lnetconfig.yaml_emitter_set_output_netlink(emitter, nl, family, version, cmd, flags)

def yaml_parser_set_input_netlink(parser, nl, stream):
    return _lnetconfig.yaml_parser_set_input_netlink(parser, nl, stream)

def yaml_parser_get_reader_proto_version(parser):
    return _lnetconfig.yaml_parser_get_reader_proto_version(parser)

def yaml_parser_get_reader_error(parser):
    return _lnetconfig.yaml_parser_get_reader_error(parser)

def yaml_parser_log_error(parser, log, errmsg):
    return _lnetconfig.yaml_parser_log_error(parser, log, errmsg)

def yaml_emitter_log_error(emitter, log):
    return _lnetconfig.yaml_emitter_log_error(emitter, log)

def lustre_lnet_init_nw_descr(nw_descr):
    return _lnetconfig.lustre_lnet_init_nw_descr(nw_descr)

def lustre_lnet_parse_interfaces(intf_str, nw_descr):
    return _lnetconfig.lustre_lnet_parse_interfaces(intf_str, nw_descr)

def lustre_lnet_parse_nidstr(nidstr, lnet_nidlist, max_nids, err_str):
    return _lnetconfig.lustre_lnet_parse_nidstr(nidstr, lnet_nidlist, max_nids, err_str)

def lustre_lnet_add_udsp(src, dst, rte, type, action, idx, seq_no):
    return _lnetconfig.lustre_lnet_add_udsp(src, dst, rte, type, action, idx, seq_no)

def lustre_lnet_del_udsp(idx, seq_no):
    return _lnetconfig.lustre_lnet_del_udsp(idx, seq_no)

def lustre_lnet_show_udsp(idx, seq_no):
    return _lnetconfig.lustre_lnet_show_udsp(idx, seq_no)

def lustre_lnet_show_peer_debug_info(peer_nid, seq_no):
    return _lnetconfig.lustre_lnet_show_peer_debug_info(peer_nid, seq_no)

def lustre_lnet_set_peer_state(state, lpni_nid, seq_no):
    return _lnetconfig.lustre_lnet_set_peer_state(state, lpni_nid, seq_no)
MAX_NUM_SHOW_ENTRIES = _lnetconfig.MAX_NUM_SHOW_ENTRIES
LNET_MAX_STR_LEN = _lnetconfig.LNET_MAX_STR_LEN
LNET_MAX_SHOW_NUM_CPT = _lnetconfig.LNET_MAX_SHOW_NUM_CPT
LNET_MAX_SHOW_NUM_NID = _lnetconfig.LNET_MAX_SHOW_NUM_NID
LNET_RT_ALIVE = _lnetconfig.LNET_RT_ALIVE
LNET_RT_MULTI_HOP = _lnetconfig.LNET_RT_MULTI_HOP
LNET_GENL_NAME = _lnetconfig.LNET_GENL_NAME
LNET_GENL_VERSION = _lnetconfig.LNET_GENL_VERSION
LNET_CMD_UNSPEC = _lnetconfig.LNET_CMD_UNSPEC
LNET_CMD_CONFIGURE = _lnetconfig.LNET_CMD_CONFIGURE
LNET_CMD_NETS = _lnetconfig.LNET_CMD_NETS
LNET_CMD_PEERS = _lnetconfig.LNET_CMD_PEERS
LNET_CMD_ROUTES = _lnetconfig.LNET_CMD_ROUTES
LNET_CMD_CONNS = _lnetconfig.LNET_CMD_CONNS
LNET_CMD_PING = _lnetconfig.LNET_CMD_PING
__LNET_CMD_MAX_PLUS_ONE = _lnetconfig.__LNET_CMD_MAX_PLUS_ONE
class lnet_ioctl_config_lnd_cmn_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lct_version = property(_lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_version_get, _lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_version_set)
    lct_peer_timeout = property(_lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_peer_timeout_get, _lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_peer_timeout_set)
    lct_peer_tx_credits = property(_lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_peer_tx_credits_get, _lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_peer_tx_credits_set)
    lct_peer_rtr_credits = property(_lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_peer_rtr_credits_get, _lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_peer_rtr_credits_set)
    lct_max_tx_credits = property(_lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_max_tx_credits_get, _lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_lct_max_tx_credits_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_swiginit(self, _lnetconfig.new_lnet_ioctl_config_lnd_cmn_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_lnd_cmn_tunables

# Register lnet_ioctl_config_lnd_cmn_tunables in _lnetconfig:
_lnetconfig.lnet_ioctl_config_lnd_cmn_tunables_swigregister(lnet_ioctl_config_lnd_cmn_tunables)

class lnet_ioctl_config_o2iblnd_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lnd_version = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_version_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_version_set)
    lnd_peercredits_hiw = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_peercredits_hiw_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_peercredits_hiw_set)
    lnd_map_on_demand = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_map_on_demand_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_map_on_demand_set)
    lnd_concurrent_sends = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_concurrent_sends_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_concurrent_sends_set)
    lnd_fmr_pool_size = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_fmr_pool_size_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_fmr_pool_size_set)
    lnd_fmr_flush_trigger = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_fmr_flush_trigger_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_fmr_flush_trigger_set)
    lnd_fmr_cache = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_fmr_cache_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_fmr_cache_set)
    lnd_conns_per_peer = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_conns_per_peer_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_conns_per_peer_set)
    lnd_ntx = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_ntx_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_ntx_set)
    lnd_timeout = property(_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_timeout_get, _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_lnd_timeout_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_o2iblnd_tunables_swiginit(self, _lnetconfig.new_lnet_ioctl_config_o2iblnd_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_o2iblnd_tunables

# Register lnet_ioctl_config_o2iblnd_tunables in _lnetconfig:
_lnetconfig.lnet_ioctl_config_o2iblnd_tunables_swigregister(lnet_ioctl_config_o2iblnd_tunables)

class lnet_ioctl_config_kfilnd_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lnd_version = property(_lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_version_get, _lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_version_set)
    lnd_prov_major_version = property(_lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_prov_major_version_get, _lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_prov_major_version_set)
    lnd_prov_minor_version = property(_lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_prov_minor_version_get, _lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_prov_minor_version_set)
    lnd_auth_key = property(_lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_auth_key_get, _lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_auth_key_set)
    lnd_traffic_class_str = property(_lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_traffic_class_str_get, _lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_traffic_class_str_set)
    lnd_traffic_class = property(_lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_traffic_class_get, _lnetconfig.lnet_ioctl_config_kfilnd_tunables_lnd_traffic_class_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_kfilnd_tunables_swiginit(self, _lnetconfig.new_lnet_ioctl_config_kfilnd_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_kfilnd_tunables

# Register lnet_ioctl_config_kfilnd_tunables in _lnetconfig:
_lnetconfig.lnet_ioctl_config_kfilnd_tunables_swigregister(lnet_ioctl_config_kfilnd_tunables)

class lnet_ioctl_config_socklnd_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lnd_version = property(_lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_version_get, _lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_version_set)
    lnd_conns_per_peer = property(_lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_conns_per_peer_get, _lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_conns_per_peer_set)
    lnd_pad = property(_lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_pad_get, _lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_pad_set)
    lnd_timeout = property(_lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_timeout_get, _lnetconfig.lnet_ioctl_config_socklnd_tunables_lnd_timeout_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_socklnd_tunables_swiginit(self, _lnetconfig.new_lnet_ioctl_config_socklnd_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_socklnd_tunables

# Register lnet_ioctl_config_socklnd_tunables in _lnetconfig:
_lnetconfig.lnet_ioctl_config_socklnd_tunables_swigregister(lnet_ioctl_config_socklnd_tunables)

class lnet_ioctl_config_gnilnd_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lnd_version = property(_lnetconfig.lnet_ioctl_config_gnilnd_tunables_lnd_version_get, _lnetconfig.lnet_ioctl_config_gnilnd_tunables_lnd_version_set)
    lnd_timeout = property(_lnetconfig.lnet_ioctl_config_gnilnd_tunables_lnd_timeout_get, _lnetconfig.lnet_ioctl_config_gnilnd_tunables_lnd_timeout_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_gnilnd_tunables_swiginit(self, _lnetconfig.new_lnet_ioctl_config_gnilnd_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_gnilnd_tunables

# Register lnet_ioctl_config_gnilnd_tunables in _lnetconfig:
_lnetconfig.lnet_ioctl_config_gnilnd_tunables_swigregister(lnet_ioctl_config_gnilnd_tunables)

class lnet_lnd_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lnd_tun_u = property(_lnetconfig.lnet_lnd_tunables_lnd_tun_u_get)

    def __init__(self):
        _lnetconfig.lnet_lnd_tunables_swiginit(self, _lnetconfig.new_lnet_lnd_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_lnd_tunables

# Register lnet_lnd_tunables in _lnetconfig:
_lnetconfig.lnet_lnd_tunables_swigregister(lnet_lnd_tunables)

class lnet_lnd_tunables_lnd_tun_u(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lnd_o2ib = property(_lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_o2ib_get, _lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_o2ib_set)
    lnd_sock = property(_lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_sock_get, _lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_sock_set)
    lnd_kfi = property(_lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_kfi_get, _lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_kfi_set)
    lnd_gni = property(_lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_gni_get, _lnetconfig.lnet_lnd_tunables_lnd_tun_u_lnd_gni_set)

    def __init__(self):
        _lnetconfig.lnet_lnd_tunables_lnd_tun_u_swiginit(self, _lnetconfig.new_lnet_lnd_tunables_lnd_tun_u())
    __swig_destroy__ = _lnetconfig.delete_lnet_lnd_tunables_lnd_tun_u

# Register lnet_lnd_tunables_lnd_tun_u in _lnetconfig:
_lnetconfig.lnet_lnd_tunables_lnd_tun_u_swigregister(lnet_lnd_tunables_lnd_tun_u)

class lnet_ioctl_config_lnd_tunables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lt_cmn = property(_lnetconfig.lnet_ioctl_config_lnd_tunables_lt_cmn_get, _lnetconfig.lnet_ioctl_config_lnd_tunables_lt_cmn_set)
    lt_tun = property(_lnetconfig.lnet_ioctl_config_lnd_tunables_lt_tun_get, _lnetconfig.lnet_ioctl_config_lnd_tunables_lt_tun_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_lnd_tunables_swiginit(self, _lnetconfig.new_lnet_ioctl_config_lnd_tunables())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_lnd_tunables

# Register lnet_ioctl_config_lnd_tunables in _lnetconfig:
_lnetconfig.lnet_ioctl_config_lnd_tunables_swigregister(lnet_ioctl_config_lnd_tunables)

class lnet_ioctl_net_config(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ni_interface = property(_lnetconfig.lnet_ioctl_net_config_ni_interface_get, _lnetconfig.lnet_ioctl_net_config_ni_interface_set)
    ni_status = property(_lnetconfig.lnet_ioctl_net_config_ni_status_get, _lnetconfig.lnet_ioctl_net_config_ni_status_set)
    ni_cpts = property(_lnetconfig.lnet_ioctl_net_config_ni_cpts_get, _lnetconfig.lnet_ioctl_net_config_ni_cpts_set)
    cfg_bulk = property(_lnetconfig.lnet_ioctl_net_config_cfg_bulk_get, _lnetconfig.lnet_ioctl_net_config_cfg_bulk_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_net_config_swiginit(self, _lnetconfig.new_lnet_ioctl_net_config())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_net_config

# Register lnet_ioctl_net_config in _lnetconfig:
_lnetconfig.lnet_ioctl_net_config_swigregister(lnet_ioctl_net_config)

LNET_TINY_BUF_IDX = _lnetconfig.LNET_TINY_BUF_IDX
LNET_SMALL_BUF_IDX = _lnetconfig.LNET_SMALL_BUF_IDX
LNET_LARGE_BUF_IDX = _lnetconfig.LNET_LARGE_BUF_IDX
LNET_NRBPOOLS = _lnetconfig.LNET_NRBPOOLS
class lnet_ioctl_pool_cfg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    pl_pools = property(_lnetconfig.lnet_ioctl_pool_cfg_pl_pools_get)
    pl_routing = property(_lnetconfig.lnet_ioctl_pool_cfg_pl_routing_get, _lnetconfig.lnet_ioctl_pool_cfg_pl_routing_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_pool_cfg_swiginit(self, _lnetconfig.new_lnet_ioctl_pool_cfg())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_pool_cfg

# Register lnet_ioctl_pool_cfg in _lnetconfig:
_lnetconfig.lnet_ioctl_pool_cfg_swigregister(lnet_ioctl_pool_cfg)

class lnet_ioctl_pool_cfg_pl_pools(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    pl_npages = property(_lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_npages_get, _lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_npages_set)
    pl_nbuffers = property(_lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_nbuffers_get, _lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_nbuffers_set)
    pl_credits = property(_lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_credits_get, _lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_credits_set)
    pl_mincredits = property(_lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_mincredits_get, _lnetconfig.lnet_ioctl_pool_cfg_pl_pools_pl_mincredits_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_pool_cfg_pl_pools_swiginit(self, _lnetconfig.new_lnet_ioctl_pool_cfg_pl_pools())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_pool_cfg_pl_pools

# Register lnet_ioctl_pool_cfg_pl_pools in _lnetconfig:
_lnetconfig.lnet_ioctl_pool_cfg_pl_pools_swigregister(lnet_ioctl_pool_cfg_pl_pools)

class lnet_ioctl_ping_data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ping_hdr = property(_lnetconfig.lnet_ioctl_ping_data_ping_hdr_get, _lnetconfig.lnet_ioctl_ping_data_ping_hdr_set)
    op_param = property(_lnetconfig.lnet_ioctl_ping_data_op_param_get, _lnetconfig.lnet_ioctl_ping_data_op_param_set)
    ping_count = property(_lnetconfig.lnet_ioctl_ping_data_ping_count_get, _lnetconfig.lnet_ioctl_ping_data_ping_count_set)
    ping_flags = property(_lnetconfig.lnet_ioctl_ping_data_ping_flags_get, _lnetconfig.lnet_ioctl_ping_data_ping_flags_set)
    mr_info = property(_lnetconfig.lnet_ioctl_ping_data_mr_info_get, _lnetconfig.lnet_ioctl_ping_data_mr_info_set)
    ping_id = property(_lnetconfig.lnet_ioctl_ping_data_ping_id_get, _lnetconfig.lnet_ioctl_ping_data_ping_id_set)
    ping_buf = property(_lnetconfig.lnet_ioctl_ping_data_ping_buf_get, _lnetconfig.lnet_ioctl_ping_data_ping_buf_set)
    ping_src = property(_lnetconfig.lnet_ioctl_ping_data_ping_src_get, _lnetconfig.lnet_ioctl_ping_data_ping_src_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_ping_data_swiginit(self, _lnetconfig.new_lnet_ioctl_ping_data())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_ping_data

# Register lnet_ioctl_ping_data in _lnetconfig:
_lnetconfig.lnet_ioctl_ping_data_swigregister(lnet_ioctl_ping_data)

class lnet_ioctl_config_data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cfg_hdr = property(_lnetconfig.lnet_ioctl_config_data_cfg_hdr_get, _lnetconfig.lnet_ioctl_config_data_cfg_hdr_set)
    cfg_net = property(_lnetconfig.lnet_ioctl_config_data_cfg_net_get, _lnetconfig.lnet_ioctl_config_data_cfg_net_set)
    cfg_count = property(_lnetconfig.lnet_ioctl_config_data_cfg_count_get, _lnetconfig.lnet_ioctl_config_data_cfg_count_set)
    cfg_nid = property(_lnetconfig.lnet_ioctl_config_data_cfg_nid_get, _lnetconfig.lnet_ioctl_config_data_cfg_nid_set)
    cfg_ncpts = property(_lnetconfig.lnet_ioctl_config_data_cfg_ncpts_get, _lnetconfig.lnet_ioctl_config_data_cfg_ncpts_set)
    cfg_config_u = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_get)
    cfg_bulk = property(_lnetconfig.lnet_ioctl_config_data_cfg_bulk_get, _lnetconfig.lnet_ioctl_config_data_cfg_bulk_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_data_swiginit(self, _lnetconfig.new_lnet_ioctl_config_data())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_data

# Register lnet_ioctl_config_data in _lnetconfig:
_lnetconfig.lnet_ioctl_config_data_swigregister(lnet_ioctl_config_data)

class lnet_ioctl_config_data_cfg_config_u(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cfg_route = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_get)
    cfg_net = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_get)
    cfg_buffers = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_get)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_data_cfg_config_u_swiginit(self, _lnetconfig.new_lnet_ioctl_config_data_cfg_config_u())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_data_cfg_config_u

# Register lnet_ioctl_config_data_cfg_config_u in _lnetconfig:
_lnetconfig.lnet_ioctl_config_data_cfg_config_u_swigregister(lnet_ioctl_config_data_cfg_config_u)

class lnet_ioctl_config_data_cfg_config_u_cfg_buffers(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    buf_enable = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_enable_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_enable_set)
    buf_tiny = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_tiny_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_tiny_set)
    buf_small = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_small_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_small_set)
    buf_large = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_large_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_buf_large_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_swiginit(self, _lnetconfig.new_lnet_ioctl_config_data_cfg_config_u_cfg_buffers())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_data_cfg_config_u_cfg_buffers

# Register lnet_ioctl_config_data_cfg_config_u_cfg_buffers in _lnetconfig:
_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_buffers_swigregister(lnet_ioctl_config_data_cfg_config_u_cfg_buffers)

class lnet_ioctl_config_data_cfg_config_u_cfg_net(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    net_intf = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_intf_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_intf_set)
    net_peer_timeout = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_peer_timeout_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_peer_timeout_set)
    net_peer_tx_credits = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_peer_tx_credits_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_peer_tx_credits_set)
    net_peer_rtr_credits = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_peer_rtr_credits_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_peer_rtr_credits_set)
    net_max_tx_credits = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_max_tx_credits_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_max_tx_credits_set)
    net_cksum_algo = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_cksum_algo_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_cksum_algo_set)
    net_interface_count = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_interface_count_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_net_interface_count_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_swiginit(self, _lnetconfig.new_lnet_ioctl_config_data_cfg_config_u_cfg_net())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_data_cfg_config_u_cfg_net

# Register lnet_ioctl_config_data_cfg_config_u_cfg_net in _lnetconfig:
_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_net_swigregister(lnet_ioctl_config_data_cfg_config_u_cfg_net)

class lnet_ioctl_config_data_cfg_config_u_cfg_route(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rtr_hop = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_hop_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_hop_set)
    rtr_priority = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_priority_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_priority_set)
    rtr_flags = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_flags_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_flags_set)
    rtr_sensitivity = property(_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_sensitivity_get, _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_rtr_sensitivity_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_swiginit(self, _lnetconfig.new_lnet_ioctl_config_data_cfg_config_u_cfg_route())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_data_cfg_config_u_cfg_route

# Register lnet_ioctl_config_data_cfg_config_u_cfg_route in _lnetconfig:
_lnetconfig.lnet_ioctl_config_data_cfg_config_u_cfg_route_swigregister(lnet_ioctl_config_data_cfg_config_u_cfg_route)

class lnet_ioctl_comm_count(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ico_get_count = property(_lnetconfig.lnet_ioctl_comm_count_ico_get_count_get, _lnetconfig.lnet_ioctl_comm_count_ico_get_count_set)
    ico_put_count = property(_lnetconfig.lnet_ioctl_comm_count_ico_put_count_get, _lnetconfig.lnet_ioctl_comm_count_ico_put_count_set)
    ico_reply_count = property(_lnetconfig.lnet_ioctl_comm_count_ico_reply_count_get, _lnetconfig.lnet_ioctl_comm_count_ico_reply_count_set)
    ico_ack_count = property(_lnetconfig.lnet_ioctl_comm_count_ico_ack_count_get, _lnetconfig.lnet_ioctl_comm_count_ico_ack_count_set)
    ico_hello_count = property(_lnetconfig.lnet_ioctl_comm_count_ico_hello_count_get, _lnetconfig.lnet_ioctl_comm_count_ico_hello_count_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_comm_count_swiginit(self, _lnetconfig.new_lnet_ioctl_comm_count())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_comm_count

# Register lnet_ioctl_comm_count in _lnetconfig:
_lnetconfig.lnet_ioctl_comm_count_swigregister(lnet_ioctl_comm_count)

class lnet_ioctl_element_stats(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iel_send_count = property(_lnetconfig.lnet_ioctl_element_stats_iel_send_count_get, _lnetconfig.lnet_ioctl_element_stats_iel_send_count_set)
    iel_recv_count = property(_lnetconfig.lnet_ioctl_element_stats_iel_recv_count_get, _lnetconfig.lnet_ioctl_element_stats_iel_recv_count_set)
    iel_drop_count = property(_lnetconfig.lnet_ioctl_element_stats_iel_drop_count_get, _lnetconfig.lnet_ioctl_element_stats_iel_drop_count_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_element_stats_swiginit(self, _lnetconfig.new_lnet_ioctl_element_stats())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_element_stats

# Register lnet_ioctl_element_stats in _lnetconfig:
_lnetconfig.lnet_ioctl_element_stats_swigregister(lnet_ioctl_element_stats)

LNET_HEALTH_TYPE_LOCAL_NI = _lnetconfig.LNET_HEALTH_TYPE_LOCAL_NI
LNET_HEALTH_TYPE_PEER_NI = _lnetconfig.LNET_HEALTH_TYPE_PEER_NI
class lnet_ioctl_local_ni_hstats(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hlni_hdr = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_hdr_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_hdr_set)
    hlni_nid = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_nid_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_nid_set)
    hlni_local_interrupt = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_interrupt_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_interrupt_set)
    hlni_local_dropped = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_dropped_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_dropped_set)
    hlni_local_aborted = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_aborted_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_aborted_set)
    hlni_local_no_route = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_no_route_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_no_route_set)
    hlni_local_timeout = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_timeout_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_timeout_set)
    hlni_local_error = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_error_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_local_error_set)
    hlni_fatal_error = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_fatal_error_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_fatal_error_set)
    hlni_health_value = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_health_value_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_health_value_set)
    hlni_ping_count = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_ping_count_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_ping_count_set)
    hlni_next_ping = property(_lnetconfig.lnet_ioctl_local_ni_hstats_hlni_next_ping_get, _lnetconfig.lnet_ioctl_local_ni_hstats_hlni_next_ping_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_local_ni_hstats_swiginit(self, _lnetconfig.new_lnet_ioctl_local_ni_hstats())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_local_ni_hstats

# Register lnet_ioctl_local_ni_hstats in _lnetconfig:
_lnetconfig.lnet_ioctl_local_ni_hstats_swigregister(lnet_ioctl_local_ni_hstats)

class lnet_ioctl_peer_ni_hstats(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hlpni_remote_dropped = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_remote_dropped_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_remote_dropped_set)
    hlpni_remote_timeout = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_remote_timeout_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_remote_timeout_set)
    hlpni_remote_error = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_remote_error_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_remote_error_set)
    hlpni_network_timeout = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_network_timeout_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_network_timeout_set)
    hlpni_health_value = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_health_value_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_health_value_set)
    hlpni_ping_count = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_ping_count_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_ping_count_set)
    hlpni_next_ping = property(_lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_next_ping_get, _lnetconfig.lnet_ioctl_peer_ni_hstats_hlpni_next_ping_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_peer_ni_hstats_swiginit(self, _lnetconfig.new_lnet_ioctl_peer_ni_hstats())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_peer_ni_hstats

# Register lnet_ioctl_peer_ni_hstats in _lnetconfig:
_lnetconfig.lnet_ioctl_peer_ni_hstats_swigregister(lnet_ioctl_peer_ni_hstats)

class lnet_ioctl_element_msg_stats(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    im_hdr = property(_lnetconfig.lnet_ioctl_element_msg_stats_im_hdr_get, _lnetconfig.lnet_ioctl_element_msg_stats_im_hdr_set)
    im_idx = property(_lnetconfig.lnet_ioctl_element_msg_stats_im_idx_get, _lnetconfig.lnet_ioctl_element_msg_stats_im_idx_set)
    im_send_stats = property(_lnetconfig.lnet_ioctl_element_msg_stats_im_send_stats_get, _lnetconfig.lnet_ioctl_element_msg_stats_im_send_stats_set)
    im_recv_stats = property(_lnetconfig.lnet_ioctl_element_msg_stats_im_recv_stats_get, _lnetconfig.lnet_ioctl_element_msg_stats_im_recv_stats_set)
    im_drop_stats = property(_lnetconfig.lnet_ioctl_element_msg_stats_im_drop_stats_get, _lnetconfig.lnet_ioctl_element_msg_stats_im_drop_stats_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_element_msg_stats_swiginit(self, _lnetconfig.new_lnet_ioctl_element_msg_stats())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_element_msg_stats

# Register lnet_ioctl_element_msg_stats in _lnetconfig:
_lnetconfig.lnet_ioctl_element_msg_stats_swigregister(lnet_ioctl_element_msg_stats)

class lnet_ioctl_config_ni(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lic_cfg_hdr = property(_lnetconfig.lnet_ioctl_config_ni_lic_cfg_hdr_get, _lnetconfig.lnet_ioctl_config_ni_lic_cfg_hdr_set)
    lic_nid = property(_lnetconfig.lnet_ioctl_config_ni_lic_nid_get, _lnetconfig.lnet_ioctl_config_ni_lic_nid_set)
    lic_ni_intf = property(_lnetconfig.lnet_ioctl_config_ni_lic_ni_intf_get, _lnetconfig.lnet_ioctl_config_ni_lic_ni_intf_set)
    lic_legacy_ip2nets = property(_lnetconfig.lnet_ioctl_config_ni_lic_legacy_ip2nets_get, _lnetconfig.lnet_ioctl_config_ni_lic_legacy_ip2nets_set)
    lic_cpts = property(_lnetconfig.lnet_ioctl_config_ni_lic_cpts_get, _lnetconfig.lnet_ioctl_config_ni_lic_cpts_set)
    lic_ncpts = property(_lnetconfig.lnet_ioctl_config_ni_lic_ncpts_get, _lnetconfig.lnet_ioctl_config_ni_lic_ncpts_set)
    lic_status = property(_lnetconfig.lnet_ioctl_config_ni_lic_status_get, _lnetconfig.lnet_ioctl_config_ni_lic_status_set)
    lic_idx = property(_lnetconfig.lnet_ioctl_config_ni_lic_idx_get, _lnetconfig.lnet_ioctl_config_ni_lic_idx_set)
    lic_dev_cpt = property(_lnetconfig.lnet_ioctl_config_ni_lic_dev_cpt_get, _lnetconfig.lnet_ioctl_config_ni_lic_dev_cpt_set)
    pad = property(_lnetconfig.lnet_ioctl_config_ni_pad_get, _lnetconfig.lnet_ioctl_config_ni_pad_set)
    lic_bulk = property(_lnetconfig.lnet_ioctl_config_ni_lic_bulk_get, _lnetconfig.lnet_ioctl_config_ni_lic_bulk_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_config_ni_swiginit(self, _lnetconfig.new_lnet_ioctl_config_ni())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_config_ni

# Register lnet_ioctl_config_ni in _lnetconfig:
_lnetconfig.lnet_ioctl_config_ni_swigregister(lnet_ioctl_config_ni)

class lnet_peer_ni_credit_info(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cr_aliveness = property(_lnetconfig.lnet_peer_ni_credit_info_cr_aliveness_get, _lnetconfig.lnet_peer_ni_credit_info_cr_aliveness_set)
    cr_refcount = property(_lnetconfig.lnet_peer_ni_credit_info_cr_refcount_get, _lnetconfig.lnet_peer_ni_credit_info_cr_refcount_set)
    cr_ni_peer_tx_credits = property(_lnetconfig.lnet_peer_ni_credit_info_cr_ni_peer_tx_credits_get, _lnetconfig.lnet_peer_ni_credit_info_cr_ni_peer_tx_credits_set)
    cr_peer_tx_credits = property(_lnetconfig.lnet_peer_ni_credit_info_cr_peer_tx_credits_get, _lnetconfig.lnet_peer_ni_credit_info_cr_peer_tx_credits_set)
    cr_peer_min_tx_credits = property(_lnetconfig.lnet_peer_ni_credit_info_cr_peer_min_tx_credits_get, _lnetconfig.lnet_peer_ni_credit_info_cr_peer_min_tx_credits_set)
    cr_peer_tx_qnob = property(_lnetconfig.lnet_peer_ni_credit_info_cr_peer_tx_qnob_get, _lnetconfig.lnet_peer_ni_credit_info_cr_peer_tx_qnob_set)
    cr_peer_rtr_credits = property(_lnetconfig.lnet_peer_ni_credit_info_cr_peer_rtr_credits_get, _lnetconfig.lnet_peer_ni_credit_info_cr_peer_rtr_credits_set)
    cr_peer_min_rtr_credits = property(_lnetconfig.lnet_peer_ni_credit_info_cr_peer_min_rtr_credits_get, _lnetconfig.lnet_peer_ni_credit_info_cr_peer_min_rtr_credits_set)
    cr_ncpt = property(_lnetconfig.lnet_peer_ni_credit_info_cr_ncpt_get, _lnetconfig.lnet_peer_ni_credit_info_cr_ncpt_set)

    def __init__(self):
        _lnetconfig.lnet_peer_ni_credit_info_swiginit(self, _lnetconfig.new_lnet_peer_ni_credit_info())
    __swig_destroy__ = _lnetconfig.delete_lnet_peer_ni_credit_info

# Register lnet_peer_ni_credit_info in _lnetconfig:
_lnetconfig.lnet_peer_ni_credit_info_swigregister(lnet_peer_ni_credit_info)

class lnet_ioctl_peer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    pr_hdr = property(_lnetconfig.lnet_ioctl_peer_pr_hdr_get, _lnetconfig.lnet_ioctl_peer_pr_hdr_set)
    pr_count = property(_lnetconfig.lnet_ioctl_peer_pr_count_get, _lnetconfig.lnet_ioctl_peer_pr_count_set)
    pr_pad = property(_lnetconfig.lnet_ioctl_peer_pr_pad_get, _lnetconfig.lnet_ioctl_peer_pr_pad_set)
    pr_nid = property(_lnetconfig.lnet_ioctl_peer_pr_nid_get, _lnetconfig.lnet_ioctl_peer_pr_nid_set)
    pr_lnd_u = property(_lnetconfig.lnet_ioctl_peer_pr_lnd_u_get)

    def __init__(self):
        _lnetconfig.lnet_ioctl_peer_swiginit(self, _lnetconfig.new_lnet_ioctl_peer())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_peer

# Register lnet_ioctl_peer in _lnetconfig:
_lnetconfig.lnet_ioctl_peer_swigregister(lnet_ioctl_peer)

class lnet_ioctl_peer_pr_lnd_u(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    pr_peer_credits = property(_lnetconfig.lnet_ioctl_peer_pr_lnd_u_pr_peer_credits_get, _lnetconfig.lnet_ioctl_peer_pr_lnd_u_pr_peer_credits_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_peer_pr_lnd_u_swiginit(self, _lnetconfig.new_lnet_ioctl_peer_pr_lnd_u())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_peer_pr_lnd_u

# Register lnet_ioctl_peer_pr_lnd_u in _lnetconfig:
_lnetconfig.lnet_ioctl_peer_pr_lnd_u_swigregister(lnet_ioctl_peer_pr_lnd_u)

class lnet_ioctl_peer_cfg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    prcfg_hdr = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_hdr_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_hdr_set)
    prcfg_prim_nid = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_prim_nid_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_prim_nid_set)
    prcfg_cfg_nid = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_cfg_nid_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_cfg_nid_set)
    prcfg_count = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_count_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_count_set)
    prcfg_mr = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_mr_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_mr_set)
    prcfg_state = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_state_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_state_set)
    prcfg_size = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_size_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_size_set)
    prcfg_bulk = property(_lnetconfig.lnet_ioctl_peer_cfg_prcfg_bulk_get, _lnetconfig.lnet_ioctl_peer_cfg_prcfg_bulk_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_peer_cfg_swiginit(self, _lnetconfig.new_lnet_ioctl_peer_cfg())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_peer_cfg

# Register lnet_ioctl_peer_cfg in _lnetconfig:
_lnetconfig.lnet_ioctl_peer_cfg_swigregister(lnet_ioctl_peer_cfg)

class lnet_ioctl_reset_health_cfg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rh_hdr = property(_lnetconfig.lnet_ioctl_reset_health_cfg_rh_hdr_get, _lnetconfig.lnet_ioctl_reset_health_cfg_rh_hdr_set)
    rh_type = property(_lnetconfig.lnet_ioctl_reset_health_cfg_rh_type_get, _lnetconfig.lnet_ioctl_reset_health_cfg_rh_type_set)
    rh_all = property(_lnetconfig.lnet_ioctl_reset_health_cfg_rh_all_get, _lnetconfig.lnet_ioctl_reset_health_cfg_rh_all_set)
    rh_value = property(_lnetconfig.lnet_ioctl_reset_health_cfg_rh_value_get, _lnetconfig.lnet_ioctl_reset_health_cfg_rh_value_set)
    rh_nid = property(_lnetconfig.lnet_ioctl_reset_health_cfg_rh_nid_get, _lnetconfig.lnet_ioctl_reset_health_cfg_rh_nid_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_reset_health_cfg_swiginit(self, _lnetconfig.new_lnet_ioctl_reset_health_cfg())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_reset_health_cfg

# Register lnet_ioctl_reset_health_cfg in _lnetconfig:
_lnetconfig.lnet_ioctl_reset_health_cfg_swigregister(lnet_ioctl_reset_health_cfg)

class lnet_ioctl_reset_conns_per_peer_cfg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rcpp_hdr = property(_lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_hdr_get, _lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_hdr_set)
    rcpp_all = property(_lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_all_get, _lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_all_set)
    rcpp_value = property(_lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_value_get, _lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_value_set)
    rcpp_nid = property(_lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_nid_get, _lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_rcpp_nid_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_swiginit(self, _lnetconfig.new_lnet_ioctl_reset_conns_per_peer_cfg())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_reset_conns_per_peer_cfg

# Register lnet_ioctl_reset_conns_per_peer_cfg in _lnetconfig:
_lnetconfig.lnet_ioctl_reset_conns_per_peer_cfg_swigregister(lnet_ioctl_reset_conns_per_peer_cfg)

class lnet_ioctl_recovery_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rlst_hdr = property(_lnetconfig.lnet_ioctl_recovery_list_rlst_hdr_get, _lnetconfig.lnet_ioctl_recovery_list_rlst_hdr_set)
    rlst_type = property(_lnetconfig.lnet_ioctl_recovery_list_rlst_type_get, _lnetconfig.lnet_ioctl_recovery_list_rlst_type_set)
    rlst_num_nids = property(_lnetconfig.lnet_ioctl_recovery_list_rlst_num_nids_get, _lnetconfig.lnet_ioctl_recovery_list_rlst_num_nids_set)
    rlst_nid_array = property(_lnetconfig.lnet_ioctl_recovery_list_rlst_nid_array_get, _lnetconfig.lnet_ioctl_recovery_list_rlst_nid_array_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_recovery_list_swiginit(self, _lnetconfig.new_lnet_ioctl_recovery_list())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_recovery_list

# Register lnet_ioctl_recovery_list in _lnetconfig:
_lnetconfig.lnet_ioctl_recovery_list_swigregister(lnet_ioctl_recovery_list)

class lnet_ioctl_set_value(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sv_hdr = property(_lnetconfig.lnet_ioctl_set_value_sv_hdr_get, _lnetconfig.lnet_ioctl_set_value_sv_hdr_set)
    sv_value = property(_lnetconfig.lnet_ioctl_set_value_sv_value_get, _lnetconfig.lnet_ioctl_set_value_sv_value_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_set_value_swiginit(self, _lnetconfig.new_lnet_ioctl_set_value())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_set_value

# Register lnet_ioctl_set_value in _lnetconfig:
_lnetconfig.lnet_ioctl_set_value_swigregister(lnet_ioctl_set_value)

class lnet_ioctl_lnet_stats(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    st_hdr = property(_lnetconfig.lnet_ioctl_lnet_stats_st_hdr_get, _lnetconfig.lnet_ioctl_lnet_stats_st_hdr_set)
    st_cntrs = property(_lnetconfig.lnet_ioctl_lnet_stats_st_cntrs_get, _lnetconfig.lnet_ioctl_lnet_stats_st_cntrs_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_lnet_stats_swiginit(self, _lnetconfig.new_lnet_ioctl_lnet_stats())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_lnet_stats

# Register lnet_ioctl_lnet_stats in _lnetconfig:
_lnetconfig.lnet_ioctl_lnet_stats_swigregister(lnet_ioctl_lnet_stats)

class lnet_range_expr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    re_lo = property(_lnetconfig.lnet_range_expr_re_lo_get, _lnetconfig.lnet_range_expr_re_lo_set)
    re_hi = property(_lnetconfig.lnet_range_expr_re_hi_get, _lnetconfig.lnet_range_expr_re_hi_set)
    re_stride = property(_lnetconfig.lnet_range_expr_re_stride_get, _lnetconfig.lnet_range_expr_re_stride_set)

    def __init__(self):
        _lnetconfig.lnet_range_expr_swiginit(self, _lnetconfig.new_lnet_range_expr())
    __swig_destroy__ = _lnetconfig.delete_lnet_range_expr

# Register lnet_range_expr in _lnetconfig:
_lnetconfig.lnet_range_expr_swigregister(lnet_range_expr)

class lnet_expressions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    le_count = property(_lnetconfig.lnet_expressions_le_count_get, _lnetconfig.lnet_expressions_le_count_set)

    def __init__(self):
        _lnetconfig.lnet_expressions_swiginit(self, _lnetconfig.new_lnet_expressions())
    __swig_destroy__ = _lnetconfig.delete_lnet_expressions

# Register lnet_expressions in _lnetconfig:
_lnetconfig.lnet_expressions_swigregister(lnet_expressions)

class lnet_ioctl_udsp_net_descr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ud_net_type = property(_lnetconfig.lnet_ioctl_udsp_net_descr_ud_net_type_get, _lnetconfig.lnet_ioctl_udsp_net_descr_ud_net_type_set)
    ud_net_num_expr = property(_lnetconfig.lnet_ioctl_udsp_net_descr_ud_net_num_expr_get, _lnetconfig.lnet_ioctl_udsp_net_descr_ud_net_num_expr_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_udsp_net_descr_swiginit(self, _lnetconfig.new_lnet_ioctl_udsp_net_descr())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_udsp_net_descr

# Register lnet_ioctl_udsp_net_descr in _lnetconfig:
_lnetconfig.lnet_ioctl_udsp_net_descr_swigregister(lnet_ioctl_udsp_net_descr)

class lnet_ioctl_udsp_descr_hdr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ud_descr_type = property(_lnetconfig.lnet_ioctl_udsp_descr_hdr_ud_descr_type_get, _lnetconfig.lnet_ioctl_udsp_descr_hdr_ud_descr_type_set)
    ud_descr_count = property(_lnetconfig.lnet_ioctl_udsp_descr_hdr_ud_descr_count_get, _lnetconfig.lnet_ioctl_udsp_descr_hdr_ud_descr_count_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_udsp_descr_hdr_swiginit(self, _lnetconfig.new_lnet_ioctl_udsp_descr_hdr())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_udsp_descr_hdr

# Register lnet_ioctl_udsp_descr_hdr in _lnetconfig:
_lnetconfig.lnet_ioctl_udsp_descr_hdr_swigregister(lnet_ioctl_udsp_descr_hdr)

class lnet_ioctl_udsp_descr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iud_src_hdr = property(_lnetconfig.lnet_ioctl_udsp_descr_iud_src_hdr_get, _lnetconfig.lnet_ioctl_udsp_descr_iud_src_hdr_set)
    iud_net = property(_lnetconfig.lnet_ioctl_udsp_descr_iud_net_get, _lnetconfig.lnet_ioctl_udsp_descr_iud_net_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_udsp_descr_swiginit(self, _lnetconfig.new_lnet_ioctl_udsp_descr())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_udsp_descr

# Register lnet_ioctl_udsp_descr in _lnetconfig:
_lnetconfig.lnet_ioctl_udsp_descr_swigregister(lnet_ioctl_udsp_descr)

class lnet_ioctl_udsp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iou_hdr = property(_lnetconfig.lnet_ioctl_udsp_iou_hdr_get, _lnetconfig.lnet_ioctl_udsp_iou_hdr_set)
    iou_idx = property(_lnetconfig.lnet_ioctl_udsp_iou_idx_get, _lnetconfig.lnet_ioctl_udsp_iou_idx_set)
    iou_action_type = property(_lnetconfig.lnet_ioctl_udsp_iou_action_type_get, _lnetconfig.lnet_ioctl_udsp_iou_action_type_set)
    iou_bulk_size = property(_lnetconfig.lnet_ioctl_udsp_iou_bulk_size_get, _lnetconfig.lnet_ioctl_udsp_iou_bulk_size_set)
    iou_action = property(_lnetconfig.lnet_ioctl_udsp_iou_action_get)
    iou_bulk = property(_lnetconfig.lnet_ioctl_udsp_iou_bulk_get, _lnetconfig.lnet_ioctl_udsp_iou_bulk_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_udsp_swiginit(self, _lnetconfig.new_lnet_ioctl_udsp())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_udsp

# Register lnet_ioctl_udsp in _lnetconfig:
_lnetconfig.lnet_ioctl_udsp_swigregister(lnet_ioctl_udsp)

class lnet_ioctl_udsp_iou_action(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    priority = property(_lnetconfig.lnet_ioctl_udsp_iou_action_priority_get, _lnetconfig.lnet_ioctl_udsp_iou_action_priority_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_udsp_iou_action_swiginit(self, _lnetconfig.new_lnet_ioctl_udsp_iou_action())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_udsp_iou_action

# Register lnet_ioctl_udsp_iou_action in _lnetconfig:
_lnetconfig.lnet_ioctl_udsp_iou_action_swigregister(lnet_ioctl_udsp_iou_action)

class lnet_ioctl_construct_udsp_info(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cud_hdr = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_hdr_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_hdr_set)
    cud_peer = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_peer_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_peer_set)
    cud_nid = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_nid_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_nid_set)
    cud_nid_priority = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_nid_priority_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_nid_priority_set)
    cud_net_priority = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_net_priority_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_net_priority_set)
    cud_pref_nid = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_pref_nid_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_pref_nid_set)
    cud_pref_rtr_nid = property(_lnetconfig.lnet_ioctl_construct_udsp_info_cud_pref_rtr_nid_get, _lnetconfig.lnet_ioctl_construct_udsp_info_cud_pref_rtr_nid_set)

    def __init__(self):
        _lnetconfig.lnet_ioctl_construct_udsp_info_swiginit(self, _lnetconfig.new_lnet_ioctl_construct_udsp_info())
    __swig_destroy__ = _lnetconfig.delete_lnet_ioctl_construct_udsp_info

# Register lnet_ioctl_construct_udsp_info in _lnetconfig:
_lnetconfig.lnet_ioctl_construct_udsp_info_swigregister(lnet_ioctl_construct_udsp_info)

class netstrfns(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nf_type = property(_lnetconfig.netstrfns_nf_type_get, _lnetconfig.netstrfns_nf_type_set)
    nf_name = property(_lnetconfig.netstrfns_nf_name_get, _lnetconfig.netstrfns_nf_name_set)
    nf_modname = property(_lnetconfig.netstrfns_nf_modname_get, _lnetconfig.netstrfns_nf_modname_set)
    nf_addr2str = property(_lnetconfig.netstrfns_nf_addr2str_get, _lnetconfig.netstrfns_nf_addr2str_set)
    nf_addr2str_size = property(_lnetconfig.netstrfns_nf_addr2str_size_get, _lnetconfig.netstrfns_nf_addr2str_size_set)
    nf_str2addr = property(_lnetconfig.netstrfns_nf_str2addr_get, _lnetconfig.netstrfns_nf_str2addr_set)
    nf_str2addr_size = property(_lnetconfig.netstrfns_nf_str2addr_size_get, _lnetconfig.netstrfns_nf_str2addr_size_set)
    nf_parse_addrlist = property(_lnetconfig.netstrfns_nf_parse_addrlist_get, _lnetconfig.netstrfns_nf_parse_addrlist_set)
    nf_print_addrlist = property(_lnetconfig.netstrfns_nf_print_addrlist_get, _lnetconfig.netstrfns_nf_print_addrlist_set)
    nf_match_addr = property(_lnetconfig.netstrfns_nf_match_addr_get, _lnetconfig.netstrfns_nf_match_addr_set)
    nf_min_max = property(_lnetconfig.netstrfns_nf_min_max_get, _lnetconfig.netstrfns_nf_min_max_set)
    nf_expand_addrrange = property(_lnetconfig.netstrfns_nf_expand_addrrange_get, _lnetconfig.netstrfns_nf_expand_addrrange_set)

    def __init__(self):
        _lnetconfig.netstrfns_swiginit(self, _lnetconfig.new_netstrfns())
    __swig_destroy__ = _lnetconfig.delete_netstrfns

# Register netstrfns in _lnetconfig:
_lnetconfig.netstrfns_swigregister(netstrfns)

class cfs_lstr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ls_str = property(_lnetconfig.cfs_lstr_ls_str_get, _lnetconfig.cfs_lstr_ls_str_set)
    ls_len = property(_lnetconfig.cfs_lstr_ls_len_get, _lnetconfig.cfs_lstr_ls_len_set)

    def __init__(self):
        _lnetconfig.cfs_lstr_swiginit(self, _lnetconfig.new_cfs_lstr())
    __swig_destroy__ = _lnetconfig.delete_cfs_lstr

# Register cfs_lstr in _lnetconfig:
_lnetconfig.cfs_lstr_swigregister(cfs_lstr)

class cfs_range_expr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    re_link = property(_lnetconfig.cfs_range_expr_re_link_get, _lnetconfig.cfs_range_expr_re_link_set)
    re_lo = property(_lnetconfig.cfs_range_expr_re_lo_get, _lnetconfig.cfs_range_expr_re_lo_set)
    re_hi = property(_lnetconfig.cfs_range_expr_re_hi_get, _lnetconfig.cfs_range_expr_re_hi_set)
    re_stride = property(_lnetconfig.cfs_range_expr_re_stride_get, _lnetconfig.cfs_range_expr_re_stride_set)

    def __init__(self):
        _lnetconfig.cfs_range_expr_swiginit(self, _lnetconfig.new_cfs_range_expr())
    __swig_destroy__ = _lnetconfig.delete_cfs_range_expr

# Register cfs_range_expr in _lnetconfig:
_lnetconfig.cfs_range_expr_swigregister(cfs_range_expr)

class cfs_expr_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    el_link = property(_lnetconfig.cfs_expr_list_el_link_get, _lnetconfig.cfs_expr_list_el_link_set)
    el_exprs = property(_lnetconfig.cfs_expr_list_el_exprs_get, _lnetconfig.cfs_expr_list_el_exprs_set)

    def __init__(self):
        _lnetconfig.cfs_expr_list_swiginit(self, _lnetconfig.new_cfs_expr_list())
    __swig_destroy__ = _lnetconfig.delete_cfs_expr_list

# Register cfs_expr_list in _lnetconfig:
_lnetconfig.cfs_expr_list_swigregister(cfs_expr_list)


def cfs_expr_list_values(expr_list, max, valpp):
    return _lnetconfig.cfs_expr_list_values(expr_list, max, valpp)

def cfs_gettok(next, delim, res):
    return _lnetconfig.cfs_gettok(next, delim, res)

def cfs_str2num_check(str, nob, num, min, max):
    return _lnetconfig.cfs_str2num_check(str, nob, num, min, max)

def cfs_human_readable2long(sizep, str):
    return _lnetconfig.cfs_human_readable2long(sizep, str)

def cfs_expr2str(list, str, size):
    return _lnetconfig.cfs_expr2str(list, str, size)

def cfs_expr_list_match(value, expr_list):
    return _lnetconfig.cfs_expr_list_match(value, expr_list)

def cfs_expr_list_print(buffer, count, expr_list):
    return _lnetconfig.cfs_expr_list_print(buffer, count, expr_list)

def cfs_expr_list_parse(str, len, min, max):
    return _lnetconfig.cfs_expr_list_parse(str, len, min, max)

def cfs_expr_list_free(expr_list):
    return _lnetconfig.cfs_expr_list_free(expr_list)

def cfs_expr_list_free_list(list):
    return _lnetconfig.cfs_expr_list_free_list(list)

def cfs_ip_addr_parse(str, len, list):
    return _lnetconfig.cfs_ip_addr_parse(str, len, list)

def cfs_ip_addr_range_gen(ip_list, count, ip_addr_expr):
    return _lnetconfig.cfs_ip_addr_range_gen(ip_list, count, ip_addr_expr)

def cfs_ip_addr_match(addr, list):
    return _lnetconfig.cfs_ip_addr_match(addr, list)

def cfs_expand_nidlist(nidlist, lnet_nidlist, max_nids):
    return _lnetconfig.cfs_expand_nidlist(nidlist, lnet_nidlist, max_nids)

def cfs_parse_nid_parts(str, addr, net_num, net_type):
    return _lnetconfig.cfs_parse_nid_parts(str, addr, net_num, net_type)

def cfs_abs_path(request_path):
    return _lnetconfig.cfs_abs_path(request_path)
SOCKLND = _lnetconfig.SOCKLND
O2IBLND = _lnetconfig.O2IBLND
LOLND = _lnetconfig.LOLND
GNILND = _lnetconfig.GNILND
GNIIPLND = _lnetconfig.GNIIPLND
PTL4LND = _lnetconfig.PTL4LND
KFILND = _lnetconfig.KFILND
NUM_LNDS = _lnetconfig.NUM_LNDS
LNET_NIDSTR_COUNT = _lnetconfig.LNET_NIDSTR_COUNT
LNET_NIDSTR_SIZE = _lnetconfig.LNET_NIDSTR_SIZE

def libcfs_next_nidstring():
    return _lnetconfig.libcfs_next_nidstring()

def libcfs_isknown_lnd(lnd):
    return _lnetconfig.libcfs_isknown_lnd(lnd)

def libcfs_lnd2modname(lnd):
    return _lnetconfig.libcfs_lnd2modname(lnd)

def libcfs_lnd2str_r(lnd, buf, buf_size):
    return _lnetconfig.libcfs_lnd2str_r(lnd, buf, buf_size)

def libcfs_lnd2str(lnd):
    return _lnetconfig.libcfs_lnd2str(lnd)

def libcfs_str2lnd(str):
    return _lnetconfig.libcfs_str2lnd(str)

def libcfs_net2str_r(net, buf, buf_size):
    return _lnetconfig.libcfs_net2str_r(net, buf, buf_size)

def libcfs_net2str(net):
    return _lnetconfig.libcfs_net2str(net)

def libcfs_nid2str_r(nid, buf, buf_size):
    return _lnetconfig.libcfs_nid2str_r(nid, buf, buf_size)

def libcfs_nid2str(nid):
    return _lnetconfig.libcfs_nid2str(nid)

def libcfs_nidstr_r(nid, buf, buf_size):
    return _lnetconfig.libcfs_nidstr_r(nid, buf, buf_size)

def libcfs_nidstr(nid):
    return _lnetconfig.libcfs_nidstr(nid)

def libcfs_strnid(nid, str):
    return _lnetconfig.libcfs_strnid(nid, str)

def libcfs_idstr(id):
    return _lnetconfig.libcfs_idstr(id)

def libcfs_str2net(str):
    return _lnetconfig.libcfs_str2net(str)

def libcfs_str2nid(str):
    return _lnetconfig.libcfs_str2nid(str)

def libcfs_str2anynid(nid, str):
    return _lnetconfig.libcfs_str2anynid(nid, str)

def libcfs_num_parse(str, len, list):
    return _lnetconfig.libcfs_num_parse(str, len, list)

def libcfs_id2str(id):
    return _lnetconfig.libcfs_id2str(id)

def cfs_free_nidlist(list):
    return _lnetconfig.cfs_free_nidlist(list)

def cfs_parse_nidlist(str, len, list):
    return _lnetconfig.cfs_parse_nidlist(str, len, list)

def cfs_print_nidlist(buffer, count, list):
    return _lnetconfig.cfs_print_nidlist(buffer, count, list)

def cfs_match_nid(nid, list):
    return _lnetconfig.cfs_match_nid(nid, list)

def cfs_match_net(net_id, net_type, net_num_list):
    return _lnetconfig.cfs_match_net(net_id, net_type, net_num_list)

def cfs_nidrange_find_min_max(nidlist, min_nid, max_nid, nidstr_length):
    return _lnetconfig.cfs_nidrange_find_min_max(nidlist, min_nid, max_nid, nidstr_length)


